services:
  - type: web
    name: phishing-detector
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    region: oregon
    plan: free
    branch: main
    repo: https://github.com/Srujanalanka/phishing-detector-v2

